# Generated by Django 3.2.25 on 2025-03-24 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='../default_profile_oopuxr', upload_to='images/')),
                ('content', models.TextField(blank=True)),
                ('account_type', models.IntegerField(choices=[(0, 'Social'), (1, 'Service Provider'), (2, 'Support Provider')], default=0)),
                ('verified', models.IntegerField(choices=[(0, 'Unverified'), (1, 'Requested'), (2, 'Rejected'), (3, 'Verified')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
