# Generated by Django 3.2.25 on 2025-03-25 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('reactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='content_type',
            field=models.ForeignKey(choices=[('posts', 'Post'), ('comments', 'Comment')], on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
